spring:
  application:
    name: Auth-Service

boot:
    admin:
      client:
        url:http://localhost:1111/
      
   
   datasource:
    url: jdbc:mysql://localhost:3306/ashokit_ecom
    username: root 
    password: Amruta@123

   jpa:
    hibernate:
    ddl-auto: update
    show-sql: true
   
management:
  endpoints:
      web:
        exposure:
          include: "*"
         
      
      
      
