spring:
  boot:
    admin:
      client:
        url: http://localhost:1111 

          profiles:
    active: auth-service


  datasource:
    username: root
    password: Amruta@123
    url: jdbc:mysql://localhost:3306/sbms38
     driver-class-name: com.mysql.cj.jdbc.Driver


  

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8084
